# -*- coding: utf-8 -*-
"""Topic_Modeling.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13mqLohj8MyOuclVuRn8fYw31KgxcA3qz
"""

!pip install ktrain

#import libaries 
import os
import numpy as np
import pandas as pd
import ktrain

#File uploading 
#from  sklearn.datasets import fetch_20newsgroups
from google.colab import files
uploaded = files.upload()

data=fetch_20newsgroups(subset='all')

data

#For removing Headers ,footers and quotes from dataset
remove=['headers','footers','quotes']
par_cleaned_data=fetch_20newsgroups(remove=remove)
bad_chars=['-','>','>','|']
cleaned_data=fetch_20newsgroups(remove=bad_chars)

#Viewing Dataset
cleaned_data

text_data=cleaned_data.data

text_data

#Target Names 
cleaned_data.target_names

#target data araray
targets=cleaned_data.target
targets

#Topic target catagories 
target_catagories=[cleaned_data.target_names[i] for i in targets] 
target_catagories

len(text_data),len(target_catagories)

""" **Model  Building with LDA**"""

topic_model=ktrain.text.get_topic_model(text_data,n_features=10000,lda_max_iter=10)

# Commented out IPython magic to ensure Python compatibility.
# %%time
# topic_model.print_topics()
#

# Commented out IPython magic to ensure Python compatibility.
# #Creating a thresold and filtering the dataset 
# %%time
# topic_model.build(text_data,threshold=0.40)
# fi_data=topic_model.filter(text_data)
#

topic_model.train_recommender()

fi_data

#Filtering the target Catagories 
fi_catagories=topic_model.filter(target_catagories)

fi_catagories

topic_model.visualize_documents(doc_topics=topic_model.get_doctopics())

doc_topics=topic_model.get_doctopics(topic_ids=[31,61,72])
topic_model.visualize_documents(doc_topics=doc_topics)

import numpy as np
def topic_classifier(news):
  tn=topic_model.predict([news])
  tc=topic_model.topics[np.argmax(tn)]
  
  print(tc)

topic_classifier("Aug 1, 2021 - NASA will provide coverage of the upcoming prelaunch, launch, and docking activities for the agency’s Boeing Orbital Flight Test-2 (OFT-2) mission to the International Space Station")

topic_model.train_recommender()

def topic_recomender(news):
  for i ,doc in enumerate(topic_model.recommend(news,n=7)):
    print('result #%d'% (i+1))
    print(''.join(doc['text'].split()[:600]))
    print()

topic_recomender("Aug 1, 2021 - NASA will provide coverage of the upcoming prelaunch, launch, and docking activities for the agency’s Boeing Orbital Flight Test-2 (OFT-2) mission to the International Space Station")

